#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  mkdir -p "$shome/bin"

  block compile pipenv
  pipenv run block compile yarn
  ln -nfs ../node_modules/.bin/bit "$shome/bin/"
}

bootstrap
