#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  
  block compile yarn upgrade
  ln -nfs .. "$shome/node_modules/babel-runtime/node_modules"
}

main "$@"
