#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_bit="$(bit --version 2>/dev/null || true)"
  jq -n --arg bit "$ver_bit" '{bit: $bit}'
}

version "$@"
