#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_bit="0.0.1"
  jq -n --arg bit "$ver_bit" '{bit: $bit}'
}

version "$@"
